-- ─────────────────────────────────────────────────────────────
-- Jarvis — action execution + daily briefings
--
--  * Approved actions are now actually executed (email send, Meta
--    budget change, …). Record what happened on the approval row.
--  * Daily morning briefings are generated by the worker and stored
--    here so the dashboard can play them instantly (and free).
-- ─────────────────────────────────────────────────────────────

-- ── Approval execution audit trail ───────────────────────────
alter table approvals add column if not exists executed_at timestamptz;
-- 'executed' | 'failed' | 'skipped' (no executable payload)
alter table approvals add column if not exists execution_status text;
alter table approvals add column if not exists execution_result jsonb;

-- ── Daily briefings ──────────────────────────────────────────
create table if not exists briefings (
  id            uuid primary key default gen_random_uuid(),
  briefing_date date not null unique,   -- in the app timezone
  content       text not null,          -- spoken-style text
  meta          jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

alter table briefings enable row level security;
drop policy if exists deny_all on briefings;
create policy deny_all on briefings for all
  to anon, authenticated using (false) with check (false);
